# Elden Ring - Weapons

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import ast

In [3]:
weapons_df = pd.read_csv('weapons.csv')

Este dataset se encuentra disponible en: https://www.kaggle.com/datasets/robikscube/elden-ring-ultimate-dataset

In [5]:
weapons_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307 entries, 0 to 306
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id                  307 non-null    object
 1   name                307 non-null    object
 2   image               307 non-null    object
 3   description         307 non-null    object
 4   attack              307 non-null    object
 5   defence             307 non-null    object
 6   scalesWith          307 non-null    object
 7   requiredAttributes  307 non-null    object
 8   category            307 non-null    object
 9   weight              307 non-null    float64
dtypes: float64(1), object(9)
memory usage: 24.1+ KB

Con la información que arroja la función `info()` sabemos que el dataframe se encuentra compuesto por 10 columnas: 1 de tipo float64 y 9 de tipo object, y no tiene valores nulos.

In [7]:
weapons_df

,id,name,image,description,attack,defence,scalesWith,requiredAttributes,category,weight
0,17f69c35d2cl0i1oh7zuqfb3mdvsj,Hand Axe,https://eldenring.fanapis.com/images/weapons/1...,"Commonly known as a hatchet, this smaller vari...","[{'name': 'Phy', 'amount': 113}, {'name': 'Mag...","[{'name': 'Phy', 'amount': 42}, {'name': 'Mag'...","[{'name': 'Str', 'scaling': 'D'}, {'name': 'De...","[{'name': 'Str', 'amount': 9}, {'name': 'Dex',...",Axe,3.5
1,17f69667224l0i1ohar280aeoxkl6z,Jawbone Axe,https://eldenring.fanapis.com/images/weapons/1...,Axe made from a herbivore's skull. Weapon of t...,"[{'name': 'Phy', 'amount': 124}, {'name': 'Mag...","[{'name': 'Phy', 'amount': 49}, {'name': 'Mag'...","[{'name': 'Str', 'scaling': 'D'}, {'name': 'De...","[{'name': 'Str', 'amount': 14}, {'name': 'Dex'...",Axe,5.5
2,17f695c42f0l0i1ohb4cao0qxackpu,Forked Hatchet,https://eldenring.fanapis.com/images/weapons/1...,Peculiar hatchet wielded by imps. The gently u...,"[{'name': 'Phy', 'amount': 101}, {'name': 'Mag...","[{'name': 'Phy', 'amount': 40}, {'name': 'Mag'...","[{'name': 'Str', 'scaling': 'D'}, {'name': 'De...","[{'name': 'Str', 'amount': 9}, {'name': 'Dex',...",Axe,2.5
3,17f69c6388cl0i1ohcb8denrbpuhqs,Iron Cleaver,https://eldenring.fanapis.com/images/weapons/1...,"Fairly large iron cleaver, commonly used by th...","[{'name': 'Phy', 'amount': 120}, {'name': 'Mag...","[{'name': 'Phy', 'amount': 51}, {'name': 'Mag'...","[{'name': 'Str', 'scaling': 'C'}, {'name': 'De...","[{'name': 'Str', 'amount': 15}, {'name': 'Dex'...",Axe,6.0
4,17f699dbb9dl0i1ohfs2g1wqxwja74,Battle Axe,https://eldenring.fanapis.com/images/weapons/1...,"A thick, heavy blade attached to a handle. A v...","[{'name': 'Phy', 'amount': 123}, {'name': 'Mag...","[{'name': 'Phy', 'amount': 47}, {'name': 'Mag'...","[{'name': 'Str', 'scaling': 'D'}, {'name': 'De...","[{'name': 'Str', 'amount': 12}, {'name': 'Dex'...",Axe,4.5
...,...,...,...,...,...,...,...,...,...,...
302,17f69571714l0i1ptc8s1fsagr8zf,Thorned Whip,https://eldenring.fanapis.com/images/weapons/1...,Hefty whip coverd in crimson thorns. Weapon of...,"[{'name': 'Phy', 'amount': 102}, {'name': 'Mag...","[{'name': 'Phy', 'amount': 26}, {'name': 'Mag'...","[{'name': 'Str', 'scaling': 'E'}, {'name': 'De...","[{'name': 'Str', 'amount': 8}, {'name': 'Dex',...",Whip,2.5
303,17f69c5c0bfl0i1ptlhsrovoc8dx07,Magma Whip Candlestick,https://eldenring.fanapis.com/images/weapons/1...,This ritual implement is a three pronged candl...,"[{'name': 'Phy', 'amount': 72}, {'name': 'Mag'...","[{'name': 'Phy', 'amount': 21}, {'name': 'Mag'...","[{'name': 'Str', 'scaling': 'E'}, {'name': 'De...","[{'name': 'Str', 'amount': 8}, {'name': 'Dex',...",Whip,2.5
304,17f694eefe9l0i1pto8dn7ezy61a99,Hoslow's Petal Whip,https://eldenring.fanapis.com/images/weapons/1...,Metal whip formed of razor-sharp chain-link bl...,"[{'name': 'Phy', 'amount': 110}, {'name': 'Mag...","[{'name': 'Phy', 'amount': 28}, {'name': 'Mag'...","[{'name': 'Str', 'scaling': 'D'}, {'name': 'De...","[{'name': 'Str', 'amount': 10}, {'name': 'Dex'...",Whip,3.5
305,17f696af19bl0i1ptpv0fdawl72o4yq,Giant's Red Braid,https://eldenring.fanapis.com/images/weapons/1...,Hefty whip woven from the flame-red hair of a ...,"[{'name': 'Phy', 'amount': 82}, {'name': 'Mag'...","[{'name': 'Phy', 'amount': 24}, {'name': 'Mag'...","[{'name': 'Str', 'scaling': 'D'}, {'name': 'De...","[{'name': 'Str', 'amount': 18}, {'name': 'Dex'...",Whip,2.5
306,17f69691044l0i1ptyliubsc1c29o9,Urumi,https://eldenring.fanapis.com/images/weapons/1...,"This weapon made of extremely thin, flexible b...","[{'name': 'Phy', 'amount': 101}, {'name': 'Mag...","[{'name': 'Phy', 'amount': 27}, {'name': 'Mag'...","[{'name': 'Str', 'scaling': 'E'}, {'name': 'De...","[{'name': 'Str', 'amount': 10}, {'name': 'Dex'...",Whip,3.0

Ahora que podemos ver más características del dataframe descubrimos que los registros de las columnas `attack`, `defence`, `scalesWith` y `requiredAttributes` son listas de diccionarios pero en formato object, por lo tanto, primero hay que convertir las columnas en listas para luego poder extraer su contenido y así poder analizar correctamente el dataframe en su totalidad.

Las columnas a extraer son `attack` y `requiredAttributes`, las columnas `description`, `defence` y `scalesWith` no serán tomadas en cuenta ya que no aportan valor al resultado final del análisis que se busca realizar.

In [9]:
weapons_df = weapons_df.drop(['description', 'defence', 'scalesWith'], axis=1)

## Extracción de la columna `attack`

In [11]:
# Convertir los registros de la columna attack a minusculas para evitar discrepancias
weapons_df['attack'] = weapons_df['attack'].str.lower()

# Convertir registros de la columna attack en listas
weapons_df['attack'] = weapons_df['attack'].apply(ast.literal_eval)

# Extraer las listas en un nuevo dataframe
attack_df = weapons_df['attack'].apply(pd.Series)

attack_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307 entries, 0 to 306
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       307 non-null    object
 1   1       307 non-null    object
 2   2       307 non-null    object
 3   3       307 non-null    object
 4   4       307 non-null    object
 5   5       307 non-null    object
 6   6       47 non-null     object
dtypes: object(7)
memory usage: 16.9+ KB

Este nuevo dataframe está formado por los diccionarios almacenados anteriormente en listas por la columna `attack`, cuenta con 7 columnas donde solo la última de ellas contiene valores nulos.

In [13]:
attack_df[attack_df[6].notnull()]

,0,1,2,3,4,5,6
14,"{'name': 'phy', 'amount': 135}","{'name': 'mag', 'amount': 0}","{'name': 'fire', 'amount': 0}","{'name': 'ligt', 'amount': 0}","{'name': 'holy', 'amount': 0}","{'name': 'crit', 'amount': 100}","{'name': 'rng', 'amount': 50}"
15,"{'name': 'phy', 'amount': 192}","{'name': 'mag', 'amount': 0}","{'name': 'fire', 'amount': 0}","{'name': 'ligt', 'amount': 0}","{'name': 'holy', 'amount': 0}","{'name': 'crit', 'amount': 100}","{'name': 'rng', 'amount': 50}"
16,"{'name': 'phy', 'amount': 80}","{'name': 'mag', 'amount': 0}","{'name': 'fire', 'amount': 0}","{'name': 'ligt', 'amount': 0}","{'name': 'holy', 'amount': 0}","{'name': 'crit', 'amount': 100}","{'name': 'rng', 'amount': 50}"
17,"{'name': 'phy', 'amount': 82}","{'name': 'mag', 'amount': 0}","{'name': 'fire', 'amount': 0}","{'name': 'ligt', 'amount': 0}","{'name': 'holy', 'amount': 0}","{'name': 'crit', 'amount': 100}","{'name': 'rng', 'amount': 0}"
18,"{'name': 'phy', 'amount': 40}","{'name': 'mag', 'amount': 0}","{'name': 'fire', 'amount': 0}","{'name': 'ligt', 'amount': 0}","{'name': 'holy', 'amount': 50}","{'name': 'crit', 'amount': 100}","{'name': 'rng', 'amount': 50}"
19,"{'name': 'phy', 'amount': 65}","{'name': 'mag', 'amount': 30}","{'name': 'fire', 'amount': 0}","{'name': 'ligt', 'amount': 0}","{'name': 'holy', 'amount': 0}","{'name': 'crit', 'amount': 100}","{'name': 'rng', 'amount': 50}"
20,"{'name': 'phy', 'amount': 75}","{'name': 'mag', 'amount': 0}","{'name': 'fire', 'amount': 0}","{'name': 'ligt', 'amount': 0}","{'name': 'holy', 'amount': 0}","{'name': 'crit', 'amount': 100}","{'name': 'rng', 'amount': 50}"
21,"{'name': 'phy', 'amount': 77}","{'name': 'mag', 'amount': 0}","{'name': 'fire', 'amount': 0}","{'name': 'ligt', 'amount': 0}","{'name': 'holy', 'amount': 0}","{'name': 'crit', 'amount': 100}","{'name': 'rng', 'amount': 55}"
22,"{'name': 'phy', 'amount': 70}","{'name': 'mag', 'amount': 0}","{'name': 'fire', 'amount': 0}","{'name': 'ligt', 'amount': 0}","{'name': 'holy', 'amount': 0}","{'name': 'crit', 'amount': 100}","{'name': 'rng', 'amount': 50}"
53,"{'name': 'phy', 'amount': 54}","{'name': 'mag', 'amount': 0}","{'name': 'fire', 'amount': 0}","{'name': 'ligt', 'amount': 0}","{'name': 'holy', 'amount': 0}","{'name': 'crit', 'amount': 100}","{'name': 'rng', 'amount': 42}"
54,"{'name': 'phy', 'amount': 58}","{'name': 'mag', 'amount': 0}","{'name': 'fire', 'amount': 0}","{'name': 'ligt', 'amount': 0}","{'name': 'holy', 'amount': 0}","{'name': 'crit', 'amount': 100}","{'name': 'rng', 'amount': 42}"
55,"{'name': 'phy', 'amount': 64}","{'name': 'mag', 'amount': 0}","{'name': 'fire', 'amount': 0}","{'name': 'ligt', 'amount': 0}","{'name': 'holy', 'amount': 0}","{'name': 'crit', 'amount': 100}","{'name': 'rng', 'amount': 42}"
56,"{'name': 'phy', 'amount': 65}","{'name': 'mag', 'amount': 0}","{'name': 'fire', 'amount': 0}","{'name': 'ligt', 'amount': 0}","{'name': 'holy', 'amount': 0}","{'name': 'crit', 'amount': 100}","{'name': 'rng', 'amount': 42}"
57,"{'name': 'phy', 'amount': 50}","{'name': 'mag', 'amount': 50}","{'name': 'fire', 'amount': 0}","{'name': 'ligt', 'amount': 0}","{'name': 'holy', 'amount': 0}","{'name': 'crit', 'amount': 100}","{'name': 'rng', 'amount': 42}"
59,"{'name': 'phy', 'amount': 68}","{'name': 'mag', 'amount': 0}","{'name': 'fire', 'amount': 0}","{'name': 'ligt', 'amount': 0}","{'name': 'holy', 'amount': 0}","{'name': 'crit', 'amount': 100}","{'name': 'rng', 'amount': 47}"
60,"{'name': 'phy', 'amount': 69}","{'name': 'mag', 'amount': 0}","{'name': 'fire', 'amount': 0}","{'name': 'ligt', 'amount': 0}","{'name': 'holy', 'amount': 0}","{'name': 'crit', 'amount': 100}","{'name': 'rng', 'amount': 42}"
112,"{'name': 'phy', 'amount': 25}","{'name': 'mag', 'amount': 0}","{'name': 'fire', 'amount': 0}","{'name': 'ligt', 'amount': 0}","{'name': 'holy', 'amount': 0}","{'name': 'crit', 'amount': 100}","{'name': 'sor', 'amount': 163}"
113,"{'name': 'phy', 'amount': 31}","{'name': 'mag', 'amount': 0}","{'name': 'fire', 'amount': 0}","{'name': 'ligt', 'amount': 0}","{'name': 'holy', 'amount': 0}","{'name': 'crit', 'amount': 100}","{'name': 'sor', 'amount': 168}"
115,"{'name': 'phy', 'amount': 29}","{'name': 'mag', 'amount': 0}","{'name': 'fire', 'amount': 0}","{'name': 'ligt', 'amount': 0}","{'name': 'holy', 'amount': 0}","{'name': 'crit', 'amount': 100}","{'name': 'inc', 'amount': 0}"
116,"{'name': 'phy', 'amount': 31}","{'name': 'mag', 'amount': 0}","{'name': 'fire', 'amount': 0}","{'name': 'ligt', 'amount': 0}","{'name': 'holy', 'amount': 0}","{'name': 'crit', 'amount': 0}","{'name': 'sor', 'amount': 60}"
117,"{'name': 'phy', 'amount': 24}","{'name': 'mag', 'amount': 0}","{'name': 'fire', 'amount': 0}","{'name': 'ligt', 'amount': 0}","{'name': 'holy', 'amount': 0}","{'name': 'crit', 'amount': 100}","{'name': 'sor', 'amount': 140}"
118,"{'name': 'phy', 'amount': 25}","{'name': 'mag', 'amount': 0}","{'name': 'fire', 'amount': 0}","{'name': 'ligt', 'amount': 0}","{'name': 'holy', 'amount': 0}","{'name': 'crit', 'amount': 100}","{'name': 'sor', 'amount': 166}"
119,"{'name': 'phy', 'amount': 38}","{'name': 'mag', 'amount': 0}","{'name': 'fire', 'amount': 0}","{'name': 'ligt', 'amount': 0}","{'name': 'holy', 'amount': 0}","{'name': 'crit', 'amount': 100}","{'name': 'sor', 'amount': 146}"
123,"{'name': 'phy', 'amount': 25}","{'name': 'mag', 'amount': 0}","{'name': 'fire', 'amount': 0}","{'name': 'ligt', 'amount': 0}","{'name': 'holy', 'amount': 0}","{'name': 'crit', 'amount': 100}","{'name': 'sorc', 'amount': 130}"
124,"{'name': 'phy', 'amount': 25}","{'name': 'mag', 'amount': 0}","{'name': 'fire', 'amount': 0}","{'name': 'ligt', 'amount': 0}","{'name': 'holy', 'amount': 0}","{'name': 'crit', 'amount': 100}","{'name': 'sorc', 'amount': 163}"
125,"{'name': 'phy', 'amount': 24}","{'name': 'mag', 'amount': 0}","{'name': 'fire', 'amount': 0}","{'name': 'ligt', 'amount': 0}","{'name': 'holy', 'amount': 0}","{'name': 'crit', 'amount': 100}","{'name': 'sor', 'amount': 166}"
126,"{'name': 'phy', 'amount': 24}","{'name': 'mag', 'amount': 0}","{'name': 'fire', 'amount': 0}","{'name': 'ligt', 'amount': 0}","{'name': 'holy', 'amount': 0}","{'name': 'crit', 'amount': 100}","{'name': 'sor', 'amount': 179}"
127,"{'name': 'phy', 'amount': 39}","{'name': 'mag', 'amount': 0}","{'name': 'fire', 'amount': 0}","{'name': 'ligt', 'amount': 0}","{'name': 'holy', 'amount': 0}","{'name': 'crit', 'amount': 0}","{'name': 'sorc', 'amount': 60}"
128,"{'name': 'phy', 'amount': 38}","{'name': 'mag', 'amount': 0}","{'name': 'fire', 'amount': 0}","{'name': 'ligt', 'amount': 0}","{'name': 'holy', 'amount': 0}","{'name': 'crit', 'amount': 100}","{'name': 'sor', 'amount': 127}"
129,"{'name': 'phy', 'amount': 42}","{'name': 'mag', 'amount': 0}","{'name': 'fire', 'amount': 0}","{'name': 'ligt', 'amount': 0}","{'name': 'holy', 'amount': 0}","{'name': 'crit', 'amount': 100}","{'name': 'sor', 'amount': 168}"
132,"{'name': 'phy', 'amount': 22}","{'name': 'mag', 'amount': 0}","{'name': 'fire', 'amount': 0}","{'name': 'ligt', 'amount': 0}","{'name': 'holy', 'amount': 0}","{'name': 'crit', 'amount': 100}","{'name': 'sor', 'amount': 154}"
141,"{'name': 'phy', 'amount': 120}","{'name': 'mag', 'amount': 0}","{'name': 'fire', 'amount': 0}","{'name': 'ligt', 'amount': 0}","{'name': 'holy', 'amount': 0}","{'name': 'crit', 'amount': 100}","{'name': 'rng', 'amount': 50}"
142,"{'name': 'phy', 'amount': 60}","{'name': 'mag', 'amount': 0}","{'name': 'fire', 'amount': 0}","{'name': 'ligt', 'amount': 0}","{'name': 'holy', 'amount': 65}","{'name': 'crit', 'amount': 100}","{'name': 'rng', 'amount': 50}"
143,"{'name': 'phy', 'amount': 130}","{'name': 'mag', 'amount': 0}","{'name': 'fire', 'amount': 0}","{'name': 'ligt', 'amount': 0}","{'name': 'holy', 'amount': 0}","{'name': 'crit', 'amount': 100}","{'name': 'rng', 'amount': 50}"
144,"{'name': 'phy', 'amount': 125}","{'name': 'mag', 'amount': 0}","{'name': 'fire', 'amount': 0}","{'name': 'ligt', 'amount': 0}","{'name': 'holy', 'amount': 0}","{'name': 'crit', 'amount': 100}","{'name': 'rng', 'amount': 50}"
214,"{'name': 'phy', 'amount': 65}","{'name': 'mag', 'amount': 0}","{'name': 'fire', 'amount': 0}","{'name': 'ligt', 'amount': 0}","{'name': 'holy', 'amount': 0}","{'name': 'crit', 'amount': 100}","{'name': 'rng', 'amount': 29}"
215,"{'name': 'phy', 'amount': 68}","{'name': 'mag', 'amount': 0}","{'name': 'fire', 'amount': 0}","{'name': 'ligt', 'amount': 0}","{'name': 'holy', 'amount': 0}","{'name': 'crit', 'amount': 100}","{'name': 'rng', 'amount': 25}"
216,"{'name': 'phy', 'amount': 65}","{'name': 'mag', 'amount': 0}","{'name': 'fire', 'amount': 0}","{'name': 'ligt', 'amount': 0}","{'name': 'holy', 'amount': 0}","{'name': 'crit', 'amount': 100}","{'name': 'rng', 'amount': 29}"
217,"{'name': 'phy', 'amount': 62}","{'name': 'mag', 'amount': 0}","{'name': 'fire', 'amount': 0}","{'name': 'ligt', 'amount': 0}","{'name': 'holy', 'amount': 0}","{'name': 'crit', 'amount': 100}","{'name': 'rng', 'amount': 29}"
218,"{'name': 'phy', 'amount': 65}","{'name': 'mag', 'amount': 0}","{'name': 'fire', 'amount': 0}","{'name': 'ligt', 'amount': 0}","{'name': 'holy', 'amount': 0}","{'name': 'crit', 'amount': 100}","{'name': 'rng', 'amount': 29}"
223,"{'name': 'phy', 'amount': 25}","{'name': 'mag', 'amount': 0}","{'name': 'fire', 'amount': 0}","{'name': 'ligt', 'amount': 0}","{'name': 'holy', 'amount': 0}","{'name': 'crit', 'amount': 100}","{'name': 'inc', 'amount': 114}"
224,"{'name': 'phy', 'amount': 25}","{'name': 'mag', 'amount': 0}","{'name': 'fire', 'amount': 0}","{'name': 'ligt', 'amount': 0}","{'name': 'holy', 'amount': 0}","{'name': 'crit', 'amount': 100}","{'name': 'inc', 'amount': 129}"
226,"{'name': 'phy', 'amount': 31}","{'name': 'mag', 'amount': 0}","{'name': 'fire', 'amount': 0}","{'name': 'ligt', 'amount': 0}","{'name': 'holy', 'amount': 0}","{'name': 'crit', 'amount': 100}","{'name': 'inc', 'amount': 60}"
227,"{'name': 'phy', 'amount': 24}","{'name': 'mag', 'amount': 0}","{'name': 'fire', 'amount': 0}","{'name': 'ligt', 'amount': 0}","{'name': 'holy', 'amount': 0}","{'name': 'crit', 'amount': 100}","{'name': 'inc', 'amount': 60}"
228,"{'name': 'phy', 'amount': 25}","{'name': 'mag', 'amount': 0}","{'name': 'fire', 'amount': 0}","{'name': 'ligt', 'amount': 0}","{'name': 'holy', 'amount': 15}","{'name': 'crit', 'amount': 100}","{'name': 'inc', 'amount': 60}"
229,"{'name': 'phy', 'amount': 25}","{'name': 'mag', 'amount': 0}","{'name': 'fire', 'amount': 0}","{'name': 'ligt', 'amount': 0}","{'name': 'holy', 'amount': 15}","{'name': 'crit', 'amount': 100}","{'name': 'inc', 'amount': 60}"
230,"{'name': 'phy', 'amount': 25}","{'name': 'mag', 'amount': 0}","{'name': 'fire', 'amount': 0}","{'name': 'ligt', 'amount': 0}","{'name': 'holy', 'amount': 0}","{'name': 'crit', 'amount': 100}","{'name': 'inc', 'amount': 60}"

Podemos ver que cada columna corresponde a un tipo de ataque, sin embargo la última columna no tiene un nombre fijo, variando entre Rng, Sor, Inc y Sorc. El siguiente paso es extraer el valor de `amount` de cada diccionario en una columna dedicada a cada tipo de ataque en el dataframe `weapons_df`.

Las columnas a insertar en el dataframe `weapons_df` son: `phyAttack`, `magAttack`, `fireAttack`, `lightAttack` y `holyAttack`. Los valores de última columna del nuevo dataframe no serán insertados en `weapons_df` ya que contiene demasiados valores nulos.

In [15]:
damage_types_list = ['phyAttack', 'magAttack', 'fireAttack', 'lightningAttack', 'holyAttack', 'critAttack']

for i, damage_type in enumerate(damage_types_list):
    df = attack_df[i].apply(pd.Series)
    weapons_df[damage_type] = df['amount']

del attack_df

weapons_df.head()

,id,name,image,attack,requiredAttributes,category,weight,phyAttack,magAttack,fireAttack,lightningAttack,holyAttack,critAttack
0,17f69c35d2cl0i1oh7zuqfb3mdvsj,Hand Axe,https://eldenring.fanapis.com/images/weapons/1...,"[{'name': 'phy', 'amount': 113}, {'name': 'mag...","[{'name': 'Str', 'amount': 9}, {'name': 'Dex',...",Axe,3.5,113,0,0,0,0,100
1,17f69667224l0i1ohar280aeoxkl6z,Jawbone Axe,https://eldenring.fanapis.com/images/weapons/1...,"[{'name': 'phy', 'amount': 124}, {'name': 'mag...","[{'name': 'Str', 'amount': 14}, {'name': 'Dex'...",Axe,5.5,124,0,0,0,0,100
2,17f695c42f0l0i1ohb4cao0qxackpu,Forked Hatchet,https://eldenring.fanapis.com/images/weapons/1...,"[{'name': 'phy', 'amount': 101}, {'name': 'mag...","[{'name': 'Str', 'amount': 9}, {'name': 'Dex',...",Axe,2.5,101,0,0,0,0,100
3,17f69c6388cl0i1ohcb8denrbpuhqs,Iron Cleaver,https://eldenring.fanapis.com/images/weapons/1...,"[{'name': 'phy', 'amount': 120}, {'name': 'mag...","[{'name': 'Str', 'amount': 15}, {'name': 'Dex'...",Axe,6.0,120,0,0,0,0,100
4,17f699dbb9dl0i1ohfs2g1wqxwja74,Battle Axe,https://eldenring.fanapis.com/images/weapons/1...,"[{'name': 'phy', 'amount': 123}, {'name': 'mag...","[{'name': 'Str', 'amount': 12}, {'name': 'Dex'...",Axe,4.5,123,0,0,0,0,100

## Extracción de la columna `requiredAttributes`

In [17]:
# Convertir los registros de la columna attack a minusculas para evitar discrepancias
weapons_df['requiredAttributes'] = weapons_df['requiredAttributes'].str.lower()

# Convertir registros de la columna requiredAttributes en listas
weapons_df['requiredAttributes'] = weapons_df['requiredAttributes'].apply(ast.literal_eval)

# Extraer las listas en un nuevo dataframe
required_df = weapons_df['requiredAttributes'].apply(pd.Series)

required_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307 entries, 0 to 306
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       307 non-null    object
 1   1       283 non-null    object
 2   2       87 non-null     object
 3   3       4 non-null      object
 4   4       1 non-null      object
dtypes: object(5)
memory usage: 12.1+ KB

Este nuevo dataframe está formado por los diccionarios almacenados anteriormente en listas por la columna `requiredAttributes`, cuenta con 5 columnas donde solo la primera de ellas no contiene valores nulos.

In [19]:
required_df

,0,1,2,3,4
0,"{'name': 'str', 'amount': 9}","{'name': 'dex', 'amount': 8}",NaN,NaN,NaN
1,"{'name': 'str', 'amount': 14}","{'name': 'dex', 'amount': 8}",NaN,NaN,NaN
2,"{'name': 'str', 'amount': 9}","{'name': 'dex', 'amount': 14}",NaN,NaN,NaN
3,"{'name': 'str', 'amount': 15}","{'name': 'dex', 'amount': 7}",NaN,NaN,NaN
4,"{'name': 'str', 'amount': 12}","{'name': 'dex', 'amount': 8}",NaN,NaN,NaN
...,...,...,...,...,...
302,"{'name': 'str', 'amount': 8}","{'name': 'dex', 'amount': 16}",NaN,NaN,NaN
303,"{'name': 'str', 'amount': 8}","{'name': 'dex', 'amount': 16}","{'name': 'fai', 'amount': 18}",NaN,NaN
304,"{'name': 'str', 'amount': 10}","{'name': 'dex', 'amount': 20}",NaN,NaN,NaN
305,"{'name': 'str', 'amount': 18}","{'name': 'dex', 'amount': 12}","{'name': 'fai', 'amount': 21}",NaN,NaN
306,"{'name': 'str', 'amount': 10}","{'name': 'dex', 'amount': 19}",NaN,NaN,NaN

In [20]:
required_df[(required_df[2].notnull())]

,0,1,2,3,4
5,"{'name': 'str', 'amount': 11}","{'name': 'dex', 'amount': 11}","{'name': 'arc', 'amount': 20}",NaN,NaN
9,"{'name': 'str', 'amount': 18}","{'name': 'dex', 'amount': 10}","{'name': 'int', 'amount': 18}",NaN,NaN
13,"{'name': 'str', 'amount': 24}","{'name': 'dex', 'amount': 8}","{'name': 'fai', 'amount': 22}",NaN,NaN
18,"{'name': 'str', 'amount': 8}","{'name': 'dex', 'amount': 12}","{'name': 'fai', 'amount': 14}",NaN,NaN
19,"{'name': 'str', 'amount': 10}","{'name': 'dex', 'amount': 14}","{'name': 'int', 'amount': 12}",NaN,NaN
...,...,...,...,...,...
294,"{'name': 'str', 'amount': 23}","{'name': 'dex', 'amount': 11}","{'name': 'fai', 'amount': 18}",NaN,NaN
296,"{'name': 'str', 'amount': 26}","{'name': 'dex', 'amount': 8}","{'name': 'fai', 'amount': 22}",NaN,NaN
298,"{'name': 'str', 'amount': 24}","{'name': 'dex', 'amount': 20}","{'name': 'fai', 'amount': 25}",NaN,NaN
303,"{'name': 'str', 'amount': 8}","{'name': 'dex', 'amount': 16}","{'name': 'fai', 'amount': 18}",NaN,NaN
305,"{'name': 'str', 'amount': 18}","{'name': 'dex', 'amount': 12}","{'name': 'fai', 'amount': 21}",NaN,NaN

In [21]:
required_df[(required_df[3].notnull())]

,0,1,2,3,4
146,"{'name': 'str', 'amount': 27}","{'name': 'dex', 'amount': 13}","{'name': 'fai', 'amount': 0}","{'name': '', 'amount': 20}",NaN
150,"{'name': 'str', 'amount': 15}","{'name': 'dex', 'amount': 22}","{'name': 'fai', 'amount': 0}","{'name': '', 'amount': 18}",NaN
257,"{'name': 'str', 'amount': 12}","{'name': 'dex', 'amount': 12}","{'name': 'int', 'amount': 0}","{'name': '', 'amount': 24}","{'name': 'fai', 'amount': 24}"
260,"{'name': 'str', 'amount': 10}","{'name': 'dex', 'amount': 12}","{'name': 'int', 'amount': 0}","{'name': '', 'amount': 14}",NaN

Se observa que la distribución de los diccionarios es similar a la obtenida anteriormente en la extracción de la columna `attack` excepto por la `columna 2` y la `columna 3`; ya que existen 4 registros donde la `columna 2` contiene solo los atributos y la `columna 3` contiene solo los valores correspondientes a los atributos de la `columna 2`.

In [23]:
for i in range(5):
    df = required_df[i].apply(pd.Series)
    print(f"Col {i}: {df['name'].unique()}")

Col 0: ['str' 'fai' '-' 'int']
Col 1: ['dex' 'int' nan 'fai' 'arc']
Col 2: [nan 'arc' 'int' 'fai' 'dex']
Col 3: [nan '']
Col 4: [nan 'fai']

Una vez que conocemos los atributos presentes en cada columna podemos proseguir con la creación de las nuevas columnas correspondientes a cada tipo de atributo requerido.

Las columnas a insertar en el dataframe `weapons_df` son: `strRequired`, `dexRequired`, `intRequired`, `faiRequired` y `arcRequired`.

In [25]:
# Columna 0
df = required_df[0].apply(pd.Series)
required_df['strRequired'] = df.loc[df['name'] == 'str', 'amount']
required_df['faiRequired'] = df.loc[df['name'] == 'fai', 'amount']
required_df['intRequired'] = df.loc[df['name'] == 'int', 'amount']

# Columna 1
df = required_df[1].apply(pd.Series)
required_df['dexRequired'] = df.loc[df['name'] == 'dex', 'amount']
required_df['intRequired'].fillna(df.loc[df['name'] == 'int', 'amount'], inplace=True)
required_df['faiRequired'].fillna(df.loc[df['name'] == 'fai', 'amount'], inplace=True)
required_df['arcRequired'] = df.loc[df['name'] == 'arc', 'amount']

# Columna 2
df = required_df[2].apply(pd.Series)
required_df['arcRequired'].fillna(df.loc[df['name'] == 'arc', 'amount'], inplace=True)
required_df['intRequired'].fillna(df.loc[df['name'] == 'int', 'amount'], inplace=True)
required_df['faiRequired'].fillna(df.loc[df['name'] == 'fai', 'amount'], inplace=True)
required_df['dexRequired'].fillna(df.loc[df['name'] == 'dex', 'amount'], inplace=True)

# Columna 3
df = required_df[3].apply(pd.Series)
required_df.loc[[146, 150, 257, 260]] = required_df.loc[[146, 150, 257, 260]].replace(0.0, 1)

# Columna 4
df = required_df[4].apply(pd.Series)
required_df['faiRequired'].fillna(df.loc[df['name'] == 'fai', 'amount'], inplace=True)

required_df = required_df.drop([0, 1, 2, 3, 4], axis=1)

# Reordenar columnas
required_df = required_df[['strRequired', 'dexRequired', 'intRequired', 'faiRequired', 'arcRequired']]

# Concatenar required_df con weapons_df
weapons_df = pd.concat([weapons_df, required_df], axis=1)

del required_df

weapons_df.head()

,id,name,image,attack,requiredAttributes,category,weight,phyAttack,magAttack,fireAttack,lightningAttack,holyAttack,critAttack,strRequired,dexRequired,intRequired,faiRequired,arcRequired
0,17f69c35d2cl0i1oh7zuqfb3mdvsj,Hand Axe,https://eldenring.fanapis.com/images/weapons/1...,"[{'name': 'phy', 'amount': 113}, {'name': 'mag...","[{'name': 'str', 'amount': 9}, {'name': 'dex',...",Axe,3.5,113,0,0,0,0,100,9.0,8.0,NaN,NaN,NaN
1,17f69667224l0i1ohar280aeoxkl6z,Jawbone Axe,https://eldenring.fanapis.com/images/weapons/1...,"[{'name': 'phy', 'amount': 124}, {'name': 'mag...","[{'name': 'str', 'amount': 14}, {'name': 'dex'...",Axe,5.5,124,0,0,0,0,100,14.0,8.0,NaN,NaN,NaN
2,17f695c42f0l0i1ohb4cao0qxackpu,Forked Hatchet,https://eldenring.fanapis.com/images/weapons/1...,"[{'name': 'phy', 'amount': 101}, {'name': 'mag...","[{'name': 'str', 'amount': 9}, {'name': 'dex',...",Axe,2.5,101,0,0,0,0,100,9.0,14.0,NaN,NaN,NaN
3,17f69c6388cl0i1ohcb8denrbpuhqs,Iron Cleaver,https://eldenring.fanapis.com/images/weapons/1...,"[{'name': 'phy', 'amount': 120}, {'name': 'mag...","[{'name': 'str', 'amount': 15}, {'name': 'dex'...",Axe,6.0,120,0,0,0,0,100,15.0,7.0,NaN,NaN,NaN
4,17f699dbb9dl0i1ohfs2g1wqxwja74,Battle Axe,https://eldenring.fanapis.com/images/weapons/1...,"[{'name': 'phy', 'amount': 123}, {'name': 'mag...","[{'name': 'str', 'amount': 12}, {'name': 'dex'...",Axe,4.5,123,0,0,0,0,100,12.0,8.0,NaN,NaN,NaN

Las columnas `attack` y `requiredAttributes` han sido extraidas correctamente, el siguiente paso es continuar con el procesamiento del dataframe `weapons_df`.

In [27]:
weapons_df = weapons_df.drop(['attack', 'requiredAttributes'], axis=1)

# Rellenar valores nulos con 0 en las columnas de atributos requeridos
columns_list = ['strRequired', 'dexRequired', 'intRequired', 'faiRequired', 'arcRequired']
for column in columns_list:
    weapons_df[column] = weapons_df[column].fillna(0)

In [28]:
weapons_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 307 entries, 0 to 306
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               307 non-null    object
 1   name             307 non-null    object
 2   image            307 non-null    object
 3   category         307 non-null    object
 4   weight           307 non-null    float64
 5   phyAttack        307 non-null    int64
 6   magAttack        307 non-null    int64
 7   fireAttack       307 non-null    int64
 8   lightningAttack  307 non-null    int64
 9   holyAttack       307 non-null    int64
 10  critAttack       307 non-null    int64
 11  strRequired      307 non-null    float64
 12  dexRequired      307 non-null    float64
 13  intRequired      307 non-null    float64
 14  faiRequired      307 non-null    float64
 15  arcRequired      307 non-null    float64
dtypes: float64(6), int64(6), object(4)
memory usage: 38.5+ KB

Nuevamente se verifica la integridad de los datos del dataframe. Se observa que ya no hay valores nulos, sin embargo las columnas correspondientes a los atributos requeridos están con tipo de dato float, hay que transformarlas a enteros.

In [30]:
weapons_df[['strRequired', 'dexRequired', 'intRequired', 'faiRequired', 'arcRequired']] = weapons_df[['strRequired', 'dexRequired', 'intRequired', 'faiRequired', 'arcRequired']].astype(np.int64)
weapons_df.dtypes

id                  object
name                object
image               object
category            object
weight             float64
phyAttack            int64
magAttack            int64
fireAttack           int64
lightningAttack      int64
holyAttack           int64
critAttack           int64
strRequired          int64
dexRequired          int64
intRequired          int64
faiRequired          int64
arcRequired          int64
dtype: object

In [31]:
weapons_df

,id,name,image,category,weight,phyAttack,magAttack,fireAttack,lightningAttack,holyAttack,critAttack,strRequired,dexRequired,intRequired,faiRequired,arcRequired
0,17f69c35d2cl0i1oh7zuqfb3mdvsj,Hand Axe,https://eldenring.fanapis.com/images/weapons/1...,Axe,3.5,113,0,0,0,0,100,9,8,0,0,0
1,17f69667224l0i1ohar280aeoxkl6z,Jawbone Axe,https://eldenring.fanapis.com/images/weapons/1...,Axe,5.5,124,0,0,0,0,100,14,8,0,0,0
2,17f695c42f0l0i1ohb4cao0qxackpu,Forked Hatchet,https://eldenring.fanapis.com/images/weapons/1...,Axe,2.5,101,0,0,0,0,100,9,14,0,0,0
3,17f69c6388cl0i1ohcb8denrbpuhqs,Iron Cleaver,https://eldenring.fanapis.com/images/weapons/1...,Axe,6.0,120,0,0,0,0,100,15,7,0,0,0
4,17f699dbb9dl0i1ohfs2g1wqxwja74,Battle Axe,https://eldenring.fanapis.com/images/weapons/1...,Axe,4.5,123,0,0,0,0,100,12,8,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
302,17f69571714l0i1ptc8s1fsagr8zf,Thorned Whip,https://eldenring.fanapis.com/images/weapons/1...,Whip,2.5,102,0,0,0,0,100,8,16,0,0,0
303,17f69c5c0bfl0i1ptlhsrovoc8dx07,Magma Whip Candlestick,https://eldenring.fanapis.com/images/weapons/1...,Whip,2.5,72,0,72,0,0,100,8,16,0,18,0
304,17f694eefe9l0i1pto8dn7ezy61a99,Hoslow's Petal Whip,https://eldenring.fanapis.com/images/weapons/1...,Whip,3.5,110,0,0,0,0,100,10,20,0,0,0
305,17f696af19bl0i1ptpv0fdawl72o4yq,Giant's Red Braid,https://eldenring.fanapis.com/images/weapons/1...,Whip,2.5,82,0,53,0,0,100,18,12,0,21,0
306,17f69691044l0i1ptyliubsc1c29o9,Urumi,https://eldenring.fanapis.com/images/weapons/1...,Whip,3.0,101,0,0,0,0,100,10,19,0,0,0

Una vez que el dataframe ha sido procesado podemos generar una copia en un archivo CSV con los cambios realizados para su análisis.

In [33]:
weapons_df.to_csv('weapons_cleaned.csv', index=False)